import type { Metadata } from "next";
import Link from "next/link";
import { Suspense } from "react";
import { NameGenerator } from "@/components/generator/NameGenerator";
import { ArrowIcon } from "@/components/icons";
import { JsonLd } from "@/components/shared/JsonLd";
import { getIndexableSurnames } from "@/lib/names";
import { siteUrl } from "@/lib/seo";

export const metadata: Metadata = {
  title: "Japanese Name Generator with Meanings & Surname Origins",
  description:
    "Generate authentic Japanese names with kanji, meanings, pronunciation, and surname origins. Explore Japanese girl names, boy names, and family names.",
  alternates: { canonical: "/" },
  openGraph: {
    title: "Japanese Name Generator with Meanings & Surname Origins",
    description:
      "Generate authentic Japanese names and discover the meanings, kanji, and stories behind their surnames.",
    url: "/",
  },
  twitter: {
    card: "summary",
    title: "Japanese Name Generator with Meanings & Surname Origins",
    description:
      "Generate authentic Japanese names and explore kanji meanings and surname stories.",
  },
};

const faq = [
  {
    question: "Are these names generated by AI?",
    answer:
      "No. The generator selects surnames, readings, and kanji spellings from structured local records. It never invents a reading or assembles arbitrary kanji.",
  },
  {
    question: "Why can one Japanese first name have several kanji spellings?",
    answer:
      "A reading such as Rin or Akari may be written with different accepted kanji. Each spelling contributes its own shades of meaning, so this site keeps the reading and spelling as separate data.",
  },
  {
    question: "Does a surname meaning prove a family’s ancestry?",
    answer:
      "No. Literal meanings and common origin explanations are useful context, but the same surname can arise in more than one region or lineage.",
  },
  {
    question: "Which name order is used in Japan?",
    answer:
      "Japanese order normally places the family name first. The generator uses this by default and also provides a Western-order display.",
  },
];

export default function HomePage() {
  const featured = getIndexableSurnames().slice(0, 3);
  return (
    <>
      <JsonLd
        data={{
          "@context": "https://schema.org",
          "@graph": [
            {
              "@type": "WebSite",
              name: "Japanese Names",
              url: siteUrl,
            },
            {
              "@type": "WebApplication",
              name: "Japanese Name Generator",
              url: siteUrl,
              applicationCategory: "ReferenceApplication",
              operatingSystem: "Any",
              description:
                "A browser-based generator that combines reviewed Japanese surname and first-name records.",
            },
            {
              "@type": "FAQPage",
              mainEntity: faq.map((item) => ({
                "@type": "Question",
                name: item.question,
                acceptedAnswer: { "@type": "Answer", text: item.answer },
              })),
            },
          ],
        }}
      />
      <section className="container-page pb-10 pt-10 sm:pt-14">
        <div className="mb-8 max-w-3xl">
          <p className="eyebrow">Names with context, not guesswork</p>
          <h1 className="section-title mt-3 !text-[clamp(2.5rem,8vw,4.8rem)]">
            Japanese Name Generator
          </h1>
          <p className="mt-4 max-w-2xl text-base leading-7 text-[#59645d] sm:text-lg">
            Generate authentic Japanese names and discover the meanings, kanji,
            and stories behind their surnames.
          </p>
        </div>
        <Suspense fallback={<div className="surface min-h-96 p-8">Loading the structured generator…</div>}>
          <NameGenerator />
        </Suspense>
      </section>

      <section className="container-page py-14">
        <div className="grid gap-4 md:grid-cols-3">
          {[
            {
              href: "/japanese-girl-names",
              title: "Japanese Girl Names",
              text: "Browse readings, kanji, meanings, and style labels.",
              mark: "女",
            },
            {
              href: "/japanese-boy-names",
              title: "Japanese Boy Names",
              text: "Compare modern, traditional, and timeless choices.",
              mark: "男",
            },
            {
              href: "/japanese-last-names",
              title: "Japanese Last Names",
              text: "Explore family-name meanings and evidence-aware origins.",
              mark: "姓",
            },
          ].map((item) => (
            <Link className="surface group p-6 transition-transform hover:-translate-y-0.5" href={item.href} key={item.href}>
              <span className="seal mb-10" aria-hidden="true">{item.mark}</span>
              <h2 className="text-xl font-semibold">{item.title}</h2>
              <p className="mt-2 text-sm leading-6 text-[#647068]">{item.text}</p>
              <span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#315c4b]">
                Explore <ArrowIcon className="transition-transform group-hover:translate-x-1" />
              </span>
            </Link>
          ))}
        </div>
      </section>

      <section className="border-y border-[#deddd5] bg-[#efeee8] py-16">
        <div className="container-page">
          <p className="eyebrow">Featured surname stories</p>
          <h2 className="section-title mt-2">Read beyond the literal translation</h2>
          <div className="mt-8 grid gap-4 md:grid-cols-3">
            {featured.map((surname) => (
              <Link className="surface p-6" href={`/surname/${surname.slug}`} key={surname.id}>
                <p className="japanese-display text-4xl">{surname.kanji}</p>
                <h3 className="mt-3 text-lg font-semibold">{surname.romaji}</h3>
                <p className="mt-1 text-sm font-medium text-[#a34837]">{surname.literalMeaning}</p>
                <p className="mt-4 line-clamp-3 text-sm leading-6 text-[#647068]">{surname.summary}</p>
              </Link>
            ))}
          </div>
        </div>
      </section>

      <section className="container-page grid gap-10 py-16 lg:grid-cols-[0.8fr_1.2fr]">
        <div>
          <p className="eyebrow">How Japanese names work</p>
          <h2 className="section-title mt-2">Reading, writing, and order all matter</h2>
        </div>
        <div className="grid gap-4 sm:grid-cols-2">
          {[
            ["Family name first", "In Japanese order, the surname normally comes before the given name: Yamamoto Rin."],
            ["One reading, several spellings", "A first-name reading can have multiple established kanji spellings with different meanings."],
            ["Meanings need context", "Kanji offer literal senses, but a name’s history cannot be proven from character meanings alone."],
            ["Natural combinations", "The generator uses compatible records and rule-based naturalness labels instead of a fake precision score."],
          ].map(([title, text], index) => (
            <article className="border-l border-[#b9c4bc] pl-5" key={title}>
              <span className="text-xs font-bold text-[#a34837]">0{index + 1}</span>
              <h3 className="mt-2 font-semibold">{title}</h3>
              <p className="mt-2 text-sm leading-6 text-[#647068]">{text}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="container-page py-16">
        <p className="eyebrow">FAQ</p>
        <h2 className="section-title mt-2">Good questions to ask about names</h2>
        <div className="mt-7 grid gap-3">
          {faq.map((item) => (
            <details className="surface group p-5" key={item.question}>
              <summary className="flex cursor-pointer items-center justify-between gap-4 font-semibold">
                {item.question}
                <span className="text-xl text-[#a34837] group-open:rotate-45" aria-hidden="true">+</span>
              </summary>
              <p className="mt-4 max-w-3xl text-sm leading-6 text-[#647068]">{item.answer}</p>
            </details>
          ))}
        </div>
      </section>
    </>
  );
}
