import type { Metadata } from "next";
import Link from "next/link";
import { Suspense } from "react";
import { NameGenerator } from "@/components/generator/NameGenerator";
import { ArrowIcon } from "@/components/icons";
import { SakuraMotif } from "@/components/SakuraMotif";
import { JsonLd } from "@/components/shared/JsonLd";
import { getIndexableSurnames } from "@/lib/names";
import { siteUrl } from "@/lib/seo";

export const metadata: Metadata = {
  title: "Japanese Name Generator with Meanings & Surname Origins",
  description:
    "Use our Japanese Name Generator to create authentic full names with kanji, meanings, pronunciation, and surname origins for girl, boy, and unisex ideas.",
  alternates: { canonical: null },
  openGraph: {
    title: "Japanese Name Generator with Meanings & Surname Origins",
    description:
      "Use our Japanese Name Generator to create authentic full names with kanji, meanings, pronunciation, and surname origins.",
    url: "https://japanesenames.site/",
  },
  twitter: {
    card: "summary",
    title: "Japanese Name Generator with Meanings & Surname Origins",
    description:
      "Create authentic full names with our Japanese Name Generator and explore kanji, meanings, pronunciation, and surname origins.",
  },
};

const faq = [
  {
    question: "Are these names generated by AI?",
    answer:
      "No. The generator selects surnames, readings, and kanji spellings from structured local records. It never invents a reading or assembles arbitrary kanji.",
  },
  {
    question: "Why can one Japanese first name have several kanji spellings?",
    answer:
      "A reading such as Rin or Akari may be written with different accepted kanji. Each spelling contributes its own shades of meaning, so this site keeps the reading and spelling as separate data.",
  },
  {
    question: "Does a surname meaning prove a family’s ancestry?",
    answer:
      "No. Literal meanings and common origin explanations are useful context, but the same surname can arise in more than one region or lineage.",
  },
  {
    question: "Which name order is used in Japan?",
    answer:
      "Japanese order normally places the family name first. The generator uses this by default and also provides a Western-order display.",
  },
  {
    question: "Are all generated names real Japanese names?",
    answer:
      "The surnames, readings, and kanji variations come from structured name records, while the full-name pairing is generated. A combination can be plausible without being common or belonging to a known person.",
  },
  {
    question: "Can I choose a specific kanji?",
    answer:
      "Yes. Enter one kanji and choose whether it should appear in the given name, surname, or either part. The filter keeps documented reading-and-spelling pairs instead of forcing the character into an unsupported name.",
  },
  {
    question: "Can I use these names for a character or a child?",
    answer:
      "Fiction-friendly mode supports broader creative exploration. For an important personal name, use the generator as a starting point and ask a fluent Japanese speaker or qualified naming professional to review its pronunciation, nuance, and cultural fit.",
  },
];

export default function HomePage() {
  const featured = getIndexableSurnames().slice(0, 3);
  return (
    <>
      <link rel="canonical" href="https://japanesenames.site/" />
      <JsonLd
        data={{
          "@context": "https://schema.org",
          "@graph": [
            {
              "@type": "WebSite",
              name: "Japanese Names",
              url: siteUrl,
            },
            {
              "@type": "WebApplication",
              name: "Japanese Name Generator",
              url: siteUrl,
              applicationCategory: "ReferenceApplication",
              operatingSystem: "Any",
              description:
                "A browser-based generator that combines source-backed Japanese surname and first-name records.",
            },
            {
              "@type": "FAQPage",
              mainEntity: faq.map((item) => ({
                "@type": "Question",
                name: item.question,
                acceptedAnswer: { "@type": "Answer", text: item.answer },
              })),
            },
          ],
        }}
      />
      <section className="container-page relative pb-8 pt-7 sm:pt-9">
        <SakuraMotif className="pointer-events-none absolute right-1 top-1 hidden w-44 opacity-70 sm:block lg:right-6 lg:w-52" />
        <div className="relative z-[1] mb-5">
          <h1 className="section-title !text-[clamp(2.2rem,6vw,3.8rem)]">
            Japanese Name Generator
          </h1>
          <p className="mt-3 text-base leading-6 text-[#59645d] sm:leading-7">
            Create Japanese full names from source-backed surname and given-name
            records. Filter by gender, style, meaning, name mode, or a specific
            kanji, then compare each result in kanji, hiragana, and romaji.
            Lock the surname or given name you like and generate new
            combinations without losing your choice.
          </p>
        </div>
        <Suspense fallback={<div className="surface min-h-96 p-8">Loading the structured generator…</div>}>
          <NameGenerator />
        </Suspense>
        <section
          aria-labelledby="generator-help-title"
          className="mt-8 grid gap-5 border-y border-[#deddd5] py-6 lg:grid-cols-[0.65fr_1.35fr] lg:items-start"
        >
          <div>
            <h2 className="text-xl font-semibold" id="generator-help-title">
              How to use the generator
            </h2>
            <p className="mt-2 max-w-md text-sm leading-6 text-[#647068]">
              Start broad, then keep the part you like while exploring alternatives.
            </p>
          </div>
          <ol className="grid gap-4 sm:grid-cols-3">
            {[
              [
                "Choose and generate",
                "Choose Girl, Boy, Unisex, or Any, then narrow the results by style, meaning, name mode, or a specific kanji. Leave filters open for broader variety.",
              ],
              [
                "Lock one part",
                "When one part feels right, lock the surname or first name. The next generation keeps your choice and changes the other part for easier comparison.",
              ],
              [
                "Copy or explore",
                "Compare both displayed name orders, copy the full name, save a favorite, or open a detail page to check pronunciation, meanings, and surname context.",
              ],
            ].map(([title, text], index) => (
              <li className="flex gap-3" key={title}>
                <span
                  aria-hidden="true"
                  className="grid size-7 shrink-0 place-items-center rounded-full bg-[#315c4b] text-xs font-bold text-white"
                >
                  {index + 1}
                </span>
                <div>
                  <h3 className="text-sm font-semibold">{title}</h3>
                  <p className="mt-1 text-xs leading-5 text-[#647068]">{text}</p>
                </div>
              </li>
            ))}
          </ol>
        </section>
        <section
          aria-labelledby="verification-title"
          className="mt-8 rounded-2xl border border-[#d9ddd6] bg-[#f3f4ef] p-5 sm:p-6"
        >
          <div className="grid gap-5 lg:grid-cols-[0.7fr_1.3fr] lg:items-start">
            <div>
              <p className="eyebrow">Evidence before interpretation</p>
              <h2 className="mt-2 text-xl font-semibold" id="verification-title">
                How this Japanese Name Generator verifies names
              </h2>
              <Link
                className="mt-4 inline-flex text-sm font-bold text-[#315c4b] underline underline-offset-4"
                href="/about"
              >
                Read the full data method
              </Link>
            </div>
            <div className="grid gap-4 sm:grid-cols-3">
              {[
                [
                  "Recorded spelling",
                  "JMnedict establishes the stored kanji-and-reading pair and preserves its upstream entry ID.",
                ],
                [
                  "Kanji components",
                  "KANJIDIC2 supplies dictionary glosses for each character without inventing a combined-name meaning.",
                ],
                [
                  "Clear limits",
                  "Popularity, style, family origin, and personal intent are shown only when separate evidence supports them.",
                ],
              ].map(([title, text]) => (
                <article key={title}>
                  <h3 className="text-sm font-semibold">{title}</h3>
                  <p className="mt-2 text-xs leading-5 text-[#647068]">{text}</p>
                </article>
              ))}
            </div>
          </div>
        </section>
      </section>

      <section className="container-page py-14">
        <div className="grid gap-4 md:grid-cols-3">
          {[
            {
              href: "/japanese-girl-names",
              title: "Japanese Girl Names",
              text: "Browse readings, kanji, meanings, and style labels.",
              mark: "女",
              accent: "#d59aa5",
              soft: "#f8e9ec",
            },
            {
              href: "/japanese-boy-names",
              title: "Japanese Boy Names",
              text: "Compare modern, traditional, and timeless choices.",
              mark: "男",
              accent: "#718793",
              soft: "#eaf0f2",
            },
            {
              href: "/japanese-last-names",
              title: "Japanese Last Names",
              text: "Explore family-name meanings and evidence-aware origins.",
              mark: "姓",
              accent: "#6f927f",
              soft: "#e8f0eb",
            },
          ].map((item) => (
            <Link
              className="surface group border-t-[3px] p-6 transition-transform hover:-translate-y-0.5"
              href={item.href}
              key={item.href}
              style={{ borderTopColor: item.accent }}
            >
              <span
                className="seal mb-10"
                aria-hidden="true"
                style={{
                  background: item.soft,
                  borderColor: item.accent,
                  color: item.accent,
                }}
              >
                {item.mark}
              </span>
              <h2 className="text-xl font-semibold">{item.title}</h2>
              <p className="mt-2 text-sm leading-6 text-[#647068]">{item.text}</p>
              <span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#315c4b]">
                Explore <ArrowIcon className="transition-transform group-hover:translate-x-1" />
              </span>
            </Link>
          ))}
        </div>
      </section>

      <section className="container-page pb-14">
        <div className="grid gap-5 border-t border-[#deddd5] pt-8 lg:grid-cols-[0.7fr_1.3fr]">
          <div>
            <p className="eyebrow">About the tool</p>
            <h2 className="section-title mt-2 !text-[clamp(1.8rem,4vw,2.6rem)]">
              What is the Japanese Name Generator?
            </h2>
          </div>
          <div className="max-w-3xl space-y-3 text-sm leading-6 text-[#59645d] sm:text-base sm:leading-7">
            <p>
              The Japanese Name Generator combines established first-name
              readings, documented kanji spellings, and source-backed surname
              records. It does not invent pronunciations or create names by
              joining arbitrary characters. Instead, it uses structured records
              and compatibility rules to produce useful Japanese full-name
              combinations.
            </p>
            <p>
              Each result separates the family name from the given name and
              shows kanji, hiragana, romaji, meaning notes, style, and surname
              context. You can filter by gender, style, meaning, or a specific
              kanji, then lock either part while generating new combinations.
              Compare Western and Japanese order side by side, save favorites,
              copy a full name, or open a detail page to examine a reading or
              spelling more closely.
            </p>
            <p>
              Treat every result as a careful starting point rather than proof
              that a combination is common in everyday life. Kanji can suggest
              literal meanings, but pronunciation, usage, regional variation,
              family history, and personal intention all affect how a Japanese
              name is understood.
            </p>
          </div>
        </div>
      </section>

      <section className="border-y border-[#deddd5] bg-[#efeee8] py-16">
        <div className="container-page">
          <p className="eyebrow">Featured surname stories</p>
          <h2 className="section-title mt-2">Read beyond the literal translation</h2>
          <div className="mt-8 grid gap-4 md:grid-cols-3">
            {featured.map((surname) => (
              <Link
                className="surface border-l-[3px] border-l-[#d59aa5] p-6"
                href={`/surname/${surname.slug}`}
                key={surname.id}
              >
                <div className="grid grid-cols-2 overflow-hidden rounded-xl border border-[#e3e2dc]">
                  <div className="min-w-0 bg-[#faf9f5] p-3.5">
                    <p className="text-[0.62rem] font-bold uppercase tracking-[0.08em] text-[#747d77]">
                      Romanized surname
                    </p>
                    <h3 className="mt-2 text-xl font-semibold leading-tight">
                      {surname.romaji}
                    </h3>
                  </div>
                  <div className="min-w-0 border-l border-[#e3e2dc] p-3.5">
                    <p className="text-[0.62rem] font-bold uppercase tracking-[0.08em] text-[#747d77]">
                      Japanese surname
                    </p>
                    <p className="japanese-display mt-2 text-3xl leading-tight">
                      {surname.kanji}
                    </p>
                    <p className="japanese-display mt-1 text-xs text-[#647068]">
                      {surname.hiragana}
                    </p>
                  </div>
                </div>
                <p className="mt-4 text-sm font-medium text-[#a34837]">{surname.literalMeaning}</p>
                <p className="mt-4 line-clamp-3 text-sm leading-6 text-[#647068]">{surname.summary}</p>
              </Link>
            ))}
          </div>
        </div>
      </section>

      <section className="container-page grid gap-10 py-16 lg:grid-cols-[0.8fr_1.2fr]">
        <div>
          <p className="eyebrow">How Japanese names work</p>
          <h2 className="section-title mt-2">Reading, writing, and order all matter</h2>
        </div>
        <div className="grid gap-4 sm:grid-cols-2">
          {[
            ["Family name first", "In Japanese order, the surname normally comes before the given name: Yamamoto Rin."],
            ["One reading, several spellings", "A first-name reading can have multiple established kanji spellings with different meanings."],
            ["Meanings need context", "Kanji offer literal senses, but a name’s history cannot be proven from character meanings alone."],
            ["Natural combinations", "The generator uses compatible records and rule-based naturalness labels instead of a fake precision score."],
          ].map(([title, text], index) => (
            <article className="border-l border-[#b9c4bc] pl-5" key={title}>
              <span className="text-xs font-bold text-[#a34837]">0{index + 1}</span>
              <h3 className="mt-2 font-semibold">{title}</h3>
              <p className="mt-2 text-sm leading-6 text-[#647068]">{text}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="border-y border-[#deddd5] bg-[#f7f5ef] py-16">
        <div className="container-page">
          <p className="eyebrow">Review the result</p>
          <h2 className="section-title mt-2">How to evaluate a generated Japanese name</h2>
          <div className="mt-8 grid gap-6 md:grid-cols-3">
            {[
              [
                "Start with pronunciation",
                "The same romanized sound may have several established kanji spellings, while one kanji can have different readings in names. Compare the romaji with the hiragana instead of guessing from the characters alone.",
              ],
              [
                "Read meanings in context",
                "Treat each kanji note as context rather than a one-line translation of a person. Two spellings with the same pronunciation can create different associations, and a surname’s literal meaning does not establish ancestry.",
              ],
              [
                "Consider the full name",
                "Compare the family-name-first and given-name-first forms shown together, say the complete name aloud, and review several combinations. Naturalness labels are useful guidance, not a guarantee of popularity or cultural suitability.",
              ],
            ].map(([title, text], index) => (
              <article className="surface p-6" key={title}>
                <span className="text-xs font-bold text-[#a34837]">0{index + 1}</span>
                <h3 className="mt-3 text-lg font-semibold">{title}</h3>
                <p className="mt-3 text-sm leading-6 text-[#647068]">{text}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="container-page py-16">
        <p className="eyebrow">FAQ</p>
        <h2 className="section-title mt-2">Good questions to ask about names</h2>
        <div className="mt-7 grid gap-3">
          {faq.map((item) => (
            <details className="surface group p-5" key={item.question}>
              <summary className="flex cursor-pointer items-center justify-between gap-4 font-semibold">
                {item.question}
                <span className="text-xl text-[#a34837] group-open:rotate-45" aria-hidden="true">+</span>
              </summary>
              <p className="mt-4 max-w-3xl text-sm leading-6 text-[#647068]">{item.answer}</p>
            </details>
          ))}
        </div>
      </section>
    </>
  );
}
