import type { Metadata } from "next";
import Link from "next/link";
import { Suspense } from "react";
import { NameGenerator } from "@/components/generator/NameGenerator";
import { ArrowIcon } from "@/components/icons";
import { SakuraMotif } from "@/components/SakuraMotif";
import { JsonLd } from "@/components/shared/JsonLd";
import { getIndexableSurnames } from "@/lib/names";
import { siteUrl } from "@/lib/seo";

export const metadata: Metadata = {
  title: "Japanese Name Generator with Meanings & Surname Origins",
  description:
    "Generate authentic Japanese names with kanji, meanings, pronunciation, and surname origins. Explore Japanese girl names, boy names, and family names.",
  alternates: { canonical: "/" },
  openGraph: {
    title: "Japanese Name Generator with Meanings & Surname Origins",
    description:
      "Generate authentic Japanese names and discover the meanings, kanji, and stories behind their surnames.",
    url: "/",
  },
  twitter: {
    card: "summary",
    title: "Japanese Name Generator with Meanings & Surname Origins",
    description:
      "Generate authentic Japanese names and explore kanji meanings and surname stories.",
  },
};

const faq = [
  {
    question: "Are these names generated by AI?",
    answer:
      "No. The generator selects surnames, readings, and kanji spellings from structured local records. It never invents a reading or assembles arbitrary kanji.",
  },
  {
    question: "Why can one Japanese first name have several kanji spellings?",
    answer:
      "A reading such as Rin or Akari may be written with different accepted kanji. Each spelling contributes its own shades of meaning, so this site keeps the reading and spelling as separate data.",
  },
  {
    question: "Does a surname meaning prove a family’s ancestry?",
    answer:
      "No. Literal meanings and common origin explanations are useful context, but the same surname can arise in more than one region or lineage.",
  },
  {
    question: "Which name order is used in Japan?",
    answer:
      "Japanese order normally places the family name first. The generator uses this by default and also provides a Western-order display.",
  },
];

export default function HomePage() {
  const featured = getIndexableSurnames().slice(0, 3);
  return (
    <>
      <JsonLd
        data={{
          "@context": "https://schema.org",
          "@graph": [
            {
              "@type": "WebSite",
              name: "Japanese Names",
              url: siteUrl,
            },
            {
              "@type": "WebApplication",
              name: "Japanese Name Generator",
              url: siteUrl,
              applicationCategory: "ReferenceApplication",
              operatingSystem: "Any",
              description:
                "A browser-based generator that combines reviewed Japanese surname and first-name records.",
            },
            {
              "@type": "FAQPage",
              mainEntity: faq.map((item) => ({
                "@type": "Question",
                name: item.question,
                acceptedAnswer: { "@type": "Answer", text: item.answer },
              })),
            },
          ],
        }}
      />
      <section className="container-page relative pb-8 pt-7 sm:pt-9">
        <SakuraMotif className="pointer-events-none absolute right-1 top-1 hidden w-44 opacity-70 sm:block lg:right-6 lg:w-52" />
        <div className="relative z-[1] mb-5 max-w-3xl">
          <h1 className="section-title !text-[clamp(2.2rem,6vw,3.8rem)]">
            Japanese Name Generator
          </h1>
          <p className="mt-3 max-w-2xl text-base leading-6 text-[#59645d] sm:leading-7">
            Generate authentic Japanese names and discover the meanings, kanji,
            and stories behind their surnames.
          </p>
        </div>
        <Suspense fallback={<div className="surface min-h-96 p-8">Loading the structured generator…</div>}>
          <NameGenerator />
        </Suspense>
        <section
          aria-labelledby="generator-help-title"
          className="mt-8 grid gap-5 border-y border-[#deddd5] py-6 lg:grid-cols-[0.65fr_1.35fr] lg:items-start"
        >
          <div>
            <h2 className="text-xl font-semibold" id="generator-help-title">
              How to use the generator
            </h2>
            <p className="mt-2 max-w-md text-sm leading-6 text-[#647068]">
              Start broad, then keep the part you like while exploring alternatives.
            </p>
          </div>
          <ol className="grid gap-4 sm:grid-cols-3">
            {[
              [
                "Choose and generate",
                "Set only the filters that matter to you, then generate six structured matches.",
              ],
              [
                "Lock one part",
                "Lock surname keeps the family name. Lock first name keeps the given name.",
              ],
              [
                "Copy or explore",
                "Copy the complete name, or open either detail page for meanings and context.",
              ],
            ].map(([title, text], index) => (
              <li className="flex gap-3" key={title}>
                <span
                  aria-hidden="true"
                  className="grid size-7 shrink-0 place-items-center rounded-full bg-[#315c4b] text-xs font-bold text-white"
                >
                  {index + 1}
                </span>
                <div>
                  <h3 className="text-sm font-semibold">{title}</h3>
                  <p className="mt-1 text-xs leading-5 text-[#647068]">{text}</p>
                </div>
              </li>
            ))}
          </ol>
        </section>
      </section>

      <section className="container-page py-14">
        <div className="grid gap-4 md:grid-cols-3">
          {[
            {
              href: "/japanese-girl-names",
              title: "Japanese Girl Names",
              text: "Browse readings, kanji, meanings, and style labels.",
              mark: "女",
              accent: "#d59aa5",
              soft: "#f8e9ec",
            },
            {
              href: "/japanese-boy-names",
              title: "Japanese Boy Names",
              text: "Compare modern, traditional, and timeless choices.",
              mark: "男",
              accent: "#718793",
              soft: "#eaf0f2",
            },
            {
              href: "/japanese-last-names",
              title: "Japanese Last Names",
              text: "Explore family-name meanings and evidence-aware origins.",
              mark: "姓",
              accent: "#6f927f",
              soft: "#e8f0eb",
            },
          ].map((item) => (
            <Link
              className="surface group border-t-[3px] p-6 transition-transform hover:-translate-y-0.5"
              href={item.href}
              key={item.href}
              style={{ borderTopColor: item.accent }}
            >
              <span
                className="seal mb-10"
                aria-hidden="true"
                style={{
                  background: item.soft,
                  borderColor: item.accent,
                  color: item.accent,
                }}
              >
                {item.mark}
              </span>
              <h2 className="text-xl font-semibold">{item.title}</h2>
              <p className="mt-2 text-sm leading-6 text-[#647068]">{item.text}</p>
              <span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#315c4b]">
                Explore <ArrowIcon className="transition-transform group-hover:translate-x-1" />
              </span>
            </Link>
          ))}
        </div>
      </section>

      <section className="container-page pb-14">
        <div className="grid gap-5 border-t border-[#deddd5] pt-8 lg:grid-cols-[0.7fr_1.3fr]">
          <div>
            <p className="eyebrow">About the tool</p>
            <h2 className="section-title mt-2 !text-[clamp(1.8rem,4vw,2.6rem)]">
              What is the Japanese Name Generator?
            </h2>
          </div>
          <div className="max-w-3xl space-y-3 text-sm leading-6 text-[#59645d] sm:text-base sm:leading-7">
            <p>
              Japanese Names is a reference-first generator for exploring natural
              Japanese full names. It combines reviewed surname records, established
              first-name readings, and documented kanji variations instead of
              inventing characters or pronunciations.
            </p>
            <p>
              Each result shows the name in kanji, hiragana, and romaji, together
              with its meaning, style, and surname context. You can lock either part
              to compare alternatives, then open the name or surname page for more
              detail.
            </p>
          </div>
        </div>
      </section>

      <section className="border-y border-[#deddd5] bg-[#efeee8] py-16">
        <div className="container-page">
          <p className="eyebrow">Featured surname stories</p>
          <h2 className="section-title mt-2">Read beyond the literal translation</h2>
          <div className="mt-8 grid gap-4 md:grid-cols-3">
            {featured.map((surname) => (
              <Link
                className="surface border-l-[3px] border-l-[#d59aa5] p-6"
                href={`/surname/${surname.slug}`}
                key={surname.id}
              >
                <p className="japanese-display text-4xl">{surname.kanji}</p>
                <h3 className="mt-3 text-lg font-semibold">{surname.romaji}</h3>
                <p className="mt-1 text-sm font-medium text-[#a34837]">{surname.literalMeaning}</p>
                <p className="mt-4 line-clamp-3 text-sm leading-6 text-[#647068]">{surname.summary}</p>
              </Link>
            ))}
          </div>
        </div>
      </section>

      <section className="container-page grid gap-10 py-16 lg:grid-cols-[0.8fr_1.2fr]">
        <div>
          <p className="eyebrow">How Japanese names work</p>
          <h2 className="section-title mt-2">Reading, writing, and order all matter</h2>
        </div>
        <div className="grid gap-4 sm:grid-cols-2">
          {[
            ["Family name first", "In Japanese order, the surname normally comes before the given name: Yamamoto Rin."],
            ["One reading, several spellings", "A first-name reading can have multiple established kanji spellings with different meanings."],
            ["Meanings need context", "Kanji offer literal senses, but a name’s history cannot be proven from character meanings alone."],
            ["Natural combinations", "The generator uses compatible records and rule-based naturalness labels instead of a fake precision score."],
          ].map(([title, text], index) => (
            <article className="border-l border-[#b9c4bc] pl-5" key={title}>
              <span className="text-xs font-bold text-[#a34837]">0{index + 1}</span>
              <h3 className="mt-2 font-semibold">{title}</h3>
              <p className="mt-2 text-sm leading-6 text-[#647068]">{text}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="container-page py-16">
        <p className="eyebrow">FAQ</p>
        <h2 className="section-title mt-2">Good questions to ask about names</h2>
        <div className="mt-7 grid gap-3">
          {faq.map((item) => (
            <details className="surface group p-5" key={item.question}>
              <summary className="flex cursor-pointer items-center justify-between gap-4 font-semibold">
                {item.question}
                <span className="text-xl text-[#a34837] group-open:rotate-45" aria-hidden="true">+</span>
              </summary>
              <p className="mt-4 max-w-3xl text-sm leading-6 text-[#647068]">{item.answer}</p>
            </details>
          ))}
        </div>
      </section>
    </>
  );
}
